name: CI/CD Pipeline for Node App with GCP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build the application
        run: npm run build

      # Step 5: Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 6: Configure gcloud CLI
      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/my-app .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/my-app

      # Step 8: Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/my-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated