name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
        id-token: write
        contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
            push: false
            context: backend/.
            tags: node-deploy-yacine:latest
            platforms: linux/amd64
        
      - name: Wait for server to be ready
        run: sleep 30
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: node-deploy-yacine
          image:  gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-deploy-yacine:latest
          region: europe-west1
          platform: managed
          

      

      - name: Allow unauthenticated access
        run: |
                gcloud run services add-iam-policy-binding node-deploy-yacine \
                  --member="allUsers" \
                  --role="roles/run.invoker" \
                  --region=europe-west1 \
                  --platform=managed  

      