name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
        id-token: write
        contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: node-deploy
          platforms: linux/amd64
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: node-deploy
          image: gcr.io/student-sandbox-project/node-deploy
          region: europe-west1
          platform: managed
          allow-unauthenticated: true
