name: Deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend/.
          push: false
          tags: node-deploy-test:latest
          platforms: linux/amd64
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: node-deploy-test
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-deploy-test:latest
          region: europe-west1
          platform: managed
          allow-unauthenticated: true

      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding node-deploy-test \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed